name: Generate binaries

on:
  push:
    branches:
      - issue-2130 # Change back to develop

jobs:
  gen-nodetime:
    name: "Generate nodetime binaries"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: ./scripts/gen-nodetime

      - name: Cache output for common pull-request job
        uses: actions/cache@v2
        with:
          path: ./starport/pkg/nodetime/data
          key: gen-binaries-nodetime

  gen-protoc-linux:
    name: "Generate protoc binaries for linux"
    runs-on: ${{ matrix.runner.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - runs-on: ubuntu-latest
            arch: amd64
          - runs-on: [ self-hosted, linux, arm64 ]
            arch: arm64
    steps:
      - uses: actions/checkout@v2

      - run: sudo apt install -y jq autoconf automake libtool curl make g++ unzip

      - name: Build protoc files
        run: ./scripts/gen-protoc

      - name: Cache output for common pull-request job
        uses: actions/cache@v2
        with:
          path: ./starport/pkg/protoc/data/protoc-linux-${{ matrix.runner.arch }}
          key: gen-binaries-protoc-linux-${{ matrix.runner.arch }}

  gen-protoc-darwin:
    name: "Generate protoc binaries for mac/darwin"
    runs-on: [ self-hosted, macOS ]
    defaults:
      run:
        shell: /usr/bin/arch -arch ${{ matrix.runner.arch-variant }} /bin/bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - arch-variant: arm64e
            arch: arm64
          - arch-variant: x86_64
            arch: amd64
    steps:
      - uses: actions/checkout@v2

      - run: brew install jq autoconf automake libtool

      - name: Build protoc files
        run: ./scripts/gen-protoc

      - name: Cache output for common pull-request job
        uses: actions/cache@v2
        with:
          path: ./starport/pkg/protoc/data/protoc-darwin-${{ matrix.runner.arch }}
          key: gen-binaries-protoc-darwin-${{ matrix.runner.arch }}

  gen-protoc-gen-dart-linux:
    name: "Generate protoc dart binaries for linux"
    runs-on: ${{ matrix.runner.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - runs-on: ubuntu-latest
            dart-arch: x64
            arch: amd64
          - runs-on: [self-hosted, linux, arm64]
            dart-arch: arm64
            arch: amd64
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          architecture: ${{ matrix.runner.dart-arch }}

      - name: Generate Dart files
        run: ./scripts/gen-protoc-gen-dart

      - name: Cache output for common pull-request job
        uses: actions/cache@v2
        with:
          path: ./starport/pkg/protoc-gen-dart/data/protoc-gen-dart_linux_${{ matrix.runner.arch }}
          key: gen-binaries-protoc-gen-dart-linux-${{ matrix.runner.arch }}


  gen-protoc-gen-dart-darwin:
    name: "Generate protoc dart binaries for mac/darwin"
    runs-on: [self-hosted, macOS]
    defaults:
      run:
        shell: /usr/bin/arch -arch ${{ matrix.runner.arch-variant }} /bin/bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - arch-variant: arm64e
            dart-arch: arm64
            arch: arm64
          - arch-variant: x86_64
            dart-arch: x64
            arch: amd64
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          architecture: ${{ matrix.runner.dart-arch }}

      - name: Generate Dart files
        run: ./scripts/gen-protoc-gen-dart

      - name: Cache output for common pull-request job
        uses: actions/cache@v2
        with:
          path: ./starport/pkg/protoc-gen-dart/data/protoc-gen-dart_darwin_${{ matrix.runner.arch }}
          key: gen-binaries-protoc-gen-dart-darwin-${{ matrix.runner.arch }}

  gen-pull-request:
    name: "Create pull request"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Get cache for nodetime
        uses: actions/cache@v2
        with:
          path: ./starport/pkg/nodetime/data
          key: gen-binaries-nodetime

      - name: Get cache for protoc
        uses: actions/cache@v2
        with:
          path: ./starport/pkg/protoc/data
          key: gen-binaries-protoc-

      - name: Get cache for protoc-gen-dart
        uses: actions/cache@v2
        with:
          path: ./starport/pkg/protoc-gen-dart/data
          key: gen-binaries-protoc-gen-dart-

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "feat(binaries): update binaries"
          commit-message: "feat(binaries): update binaries"
          body: "See changed files to see which binaries have been updated"
          branch: feat/gen-binaries

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"