name: Generate binaries

on:
  push:
    branches:
      - issue-2130 # Change back to develop

jobs:
  gen-nodetime:
    name: "Generate nodetime binaries"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: ./scripts/gen-nodetime

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "feat(nodetime): update binaries"
          commit-message: "feat(nodetime): update binaries"
          body: ""
          branch: feat/gen-nodetime

  gen-protoc:
    name: "Generate protoc binaries"
    runs-on: ${{ matrix.runner.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - runs-on: ubuntu-latest
            arch: amd64
            os: linux
          - runs-on: [ self-hosted, linux, arm64 ]
            arch: arm64
            os: linux
          - runs-on: [ self-hosted, macOS ]
            arch: amd64
            os: osx
          - runs-on: [ self-hosted, macOS ]
            os: osx
    defaults:
      run:
        shell: if [[ "${{ matrix.runner.os }} == "osx" ]] ; then /usr/bin/arch -arch ${{ matrix.runner.arch-variant }} /bin/bash -l {0}; else /bin/bash -l {0};
    steps:
      - uses: actions/checkout@v2

      - run: |
          if [[ "${{ matrix.runner.os }} == "osx" ]]; then
            brew install jq autoconf automake libtool
          else
            sudo apt install -y jq autoconf automake libtool curl make g++ unzip
          fi

      - name: Build protoc files
        run: ./scripts/gen-protoc

  gen-protoc-gen-dart:
    name: "Generate protoc dart binaries for linux"
    runs-on: ${{ matrix.runner.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - runs-on: ubuntu-latest
            dart-arch: x64
            arch: amd64
            os: linux
          - runs-on: [self-hosted, linux, arm64]
            dart-arch: arm64
            arch: amd64
            os: linux
          - runs-on: [self-hosted, macOS]
            dart-arch: arm64
            arch: arm64
            arch-variant: arm64e
            os: osx
          - runs-on: [self-hosted, macOS]
            dart-arch: x64
            arch: amd64
            arch-variant: x86_64
            os: osx
    defaults:
      run:
        shell: if [[ "${{ matrix.runner.os }} == "osx" ]] ; then /usr/bin/arch -arch ${{ matrix.runner.arch-variant }} /bin/bash -l {0}; else /bin/bash -l {0};
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          architecture: ${{ matrix.runner.dart-arch }}

      - name: Generate Dart files
        run: ./scripts/gen-protoc-gen-dart
