name: Generate protoc binaries

on:
  push:
    branches:
      - issue-2130 # Change back to develop

# Build instructions taken from: https://github.com/protocolbuffers/protobuf/blob/master/src/README.md

jobs:
  gen-protoc-linux:
    runs-on: ${{ matrix.runner.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - runs-on: ubuntu-latest
            arch: amd64
          - runs-on: [self-hosted, linux, arm64]
            arch: arm64
    steps:
      - uses: actions/checkout@v2

      - run: sudo apt install -y jq autoconf automake libtool curl make g++ unzip

      - name: Build protoc files
        run: ./scripts/gen-protoc

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "feat(pkg/protoc): update binaries linux ${{ matrix.runner.arch }}"
          commit-message: "feat(pkg/protoc): update binaries linux ${{ matrix.runner.arch }}"
          body: ""
          branch: feat/gen-protoc-linux-${{ matrix.runner.arch }}

  gen-protoc-darwin:
    runs-on: [self-hosted, macOS]
    defaults:
      run:
        shell: /usr/bin/arch -arch ${{ matrix.arch }} /bin/bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        arch: [ arm64e, x86_64 ]
    steps:
      - uses: actions/checkout@v2

      - run: brew install jq autoconf automake libtool

      - name: Build protoc files
        run: ./scripts/gen-protoc

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "feat(pkg/protoc): update binaries darwin ${{ matrix.arch }}"
          commit-message: "feat(pkg/protoc): update binaries darwin ${{ matrix.arch }}"
          body: ""
          branch: feat/gen-protoc-darwin-${{ matrix.arch }}

