name: Test self-hosted
on:
  push:
    branches:
      - issue-2130
jobs:
  test-self-hosted-job:
    runs-on: self-hosted
    defaults:
      run:
        shell: "/usr/bin/arch -arch arm64e /bin/bash {0}"
    steps:
      - run: |
          uname -a